service:
  name: fe-app
  port: 80
  targetPort: 8080
  type: LoadBalancer

container:
  port: 8080

image:
  # ✅ must include image name (fe-app)
  repository: us-central1-docker.pkg.dev/devops-lab-project-485312/apps/fe-app
  tag: "1.0"   # placeholder; pipeline will override via --set image.tag=<gitSHA/build#>

probes:
  readiness:
    httpGet:
      path: /healthz
      port: 8080
  liveness:
    httpGet:
      path: /healthz
      port: 8080

gkeParameters:
  projectId: devops-lab-project-485312
  clusterName: lab-gke-autopilot
  location: us-central1
  namespace: lab-internal
