nameOverride: "fe-app-lab"
fullnameOverride: "fe-app-lab"

requests:
  cpu: "100m"
  memory: "128Mi"
limits:
  cpu: "500m"
  memory: "512Mi"

service:
  name: fe-app
  port: 80
  targetPort: 8080
  type: LoadBalancer

container:
  port: 8080

image:
  repository: us-central1-docker.pkg.dev/devops-lab-project-485312/apps/lab-app-chart
  tag: "1.0" 

probes:
  readiness:
    httpGet:
      path: /healthz
      port: 8080
  liveness:
    httpGet:
      path: /healthz
      port: 8080

gkeParameters:
  projectId: devops-lab-project-485312
  clusterName: lab-gke-autopilot
  location: us-central1
  namespace: lab-internal
