app:
  name: fe-app
  namespace: default
  releaseName: fe-app

build:
  image:
    name: fe-app
    context: frontend
    dockerfile: frontend/Dockerfile

deploy:
  chart:
    repo: "github.com/your-org/reusable-helm-charts"
    name: "reusable-app"
    path: "charts/reusable-app"
  valuesFiles:
    - deploy/values.yaml
  environments:
    dev:
      valuesFiles: [deploy/values-dev.yaml]
    qa:
      valuesFiles: [deploy/values-qa.yaml]
    uat:
      valuesFiles: [deploy/values-uat.yaml]
    prod:
      valuesFiles: [deploy/values-prod.yaml]
