app:
  name: fe-app
  namespace: default
  releaseName: fe-app

build:
  image:
    name: fe-app
    context: frontend
    dockerfile: frontend/Dockerfile

deploy:
  chart:
    repo: "us-central1-docker.pkg.dev/devops-lab-project-485312/apps"
    name: "app-template"
    path: "charts/lab-app-chart"
  valuesFiles:
    - deploy/values.yaml
  environments:
    dev:
      valuesFiles: [deploy/values-dev.yaml]
